apiVersion: 1

contactPoints:
  - orgId: 1
    name: ops-discord
    receivers:
      - uid: ops-discord-receiver
        type: discord
        settings:
          url: ${DISCORD_WEBHOOK_URL}
          recipient: ${DISCORD_CHANNEL}
          title: '{{ template "default.title" . }}'
          text: '{{ template "default.message" . }}'