services:

  minio:
    image: minio/minio
    command: "minio server --address ':9000' --console-address ':9001' /data"
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_DEFAULT_BUCKETS=mimir
    volumes:
      - minio_data:/data
#    ports:
#      - "9000:9000"
#      - "9001:9001"
    networks:
      - observability

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc alias set myminio http://minio:9000 mimir supersecret;
      /usr/bin/mc mb myminio/mimir myminio/mimir-blocks myminio/mimir-alertmanager myminio/mimir-ruler 
      /usr/bin/mc mb myminio/loki-data myminio/loki-ruler;
      #/usr/bin/mc policy set public mimir mimir-blocks mimir-alertmanager mimir-ruler loki-data loki-ruler;
      exit 0;
      "
    networks:
      - observability

  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir
    depends_on:
      - minio
    volumes:
      - ./mimir/config.yml:/etc/mimir.yaml
      - mimir_data:/data
#    ports:
#      - "9009:9009"
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    ports:
      - "3200:3200"      # KYC log-push endpoint
      - "3201:3201"      # App log-push endpoint
      - "3202:3202"      # Proxy log-push endpoint
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "run", "/etc/alloy/config.alloy", "--server.http.listen-addr=0.0.0.0:12345" ]
    depends_on:
      - loki
      - mimir
    networks:
      - observability

  loki:
    image: grafana/loki:latest
#    ports:
#      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki/config.yml
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
      - mimir
    networks:
      - observability

networks:
  observability:
    name: observability
    driver: bridge

volumes:
  minio_data:
  mimir_data:
  grafana_data:
  loki_data:
  
